### ISSUE TITLE
flexgui Library directories should be persistent across launches of flexgui

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexgui#14]
When relaunching flexgui ($ wish flexgui.tcl) on macOS, any library directories that were previously added via the "Library directories..." menu option, are no longer available. The user is required to re-add those directories for each launch of flexgui. Could those directories be stored as well as changes made in the Configure Commands dialog? Should the flexgui directory contain a .config file of user mods and adds?

I'm not sure if this is the case for other OS's, since macOS is my normal config...

**Comment by totalspectrum** [comment]
I'm not able to reproduce this; for me the library directories are saved, although there was one nasty issue (the library directories dialog box could be hidden behind the main window sometimes) which I've fixed in github. 

All of the configurations are saved in a file called .flexgui.config. Since it starts with a period it doesn't normally show up in "ls"; you have to do "ls -a" to see it.

The library paths are stored in the "liblist" entry in that file. You should see that change if you start flexgui, add a file to the path, and then quit.

**Comment by dgately** [comment]
Odd, it does seem to work, now... Maybe there's something having to do with using wish to exec flexgui... Now, it is saving the library directories but is not saving the openfiles config item.

It's possible that wish is not allowing flexgui to completely finish on an exit. I'll keep looking at this.

**Comment by dgately** [comment]
Yes, the Wish app has its own menu and within that menu is, of course, the standard "Quit" item and "Command-Q" option that I as a Mac user always use to "Quit" an app.

Using flexgui's "Exit" menu item works as it should! So, can the flexgui "Exit" menu be given the Windows-style Control-X option? (it may show up as a Command-X option on macOS, but that is OK)

<img width="677" alt="flexgui_Menu" src="https://user-images.githubusercontent.com/3009364/79074168-b6fe8800-7c9f-11ea-9100-fe0b41321fe9.png">
<img width="685" alt="Wish_Menu" src="https://user-images.githubusercontent.com/3009364/79074170-bb2aa580-7c9f-11ea-93ed-873346b554b1.png">

**Comment by dgately** [comment]
Closing as user error, though "Exit" should get a Control-X or Command-X option :-)

**Comment by totalspectrum** [comment]
Actually in the current github flexgui hooks into Command-Q (which is what "Exit" should have for an accelerator: in fact on the other platforms Control-Q does show up, but on Mac I guess it refuses to give us Command-Q because WIsh owns it. But at least wish does provide a hook for it.)
